---
title: "Kwartowitz_Homework4/p15"
author: "Ellie Kwartowitz"
format: 
  html:
    embed-resources: true
editor: visual
editor_options:
  chunk_output_type: console
---

1.  Saving to RDS

    ```{r}
    #install.packages("RedditExtractoR")
    library(RedditExtractoR)
    library(tidyverse)
    library(tidytext)

    #| eval: false
    top_movies_urls <- find_thread_urls(subreddit="movies", sort_by="top")
    write_rds(top_movies_urls, "top_movies_urls.rds")
    ```

2.  Pull posts from a subreddit

    ```{r}
    top_movies_urls <- read_rds("top_movies_urls.rds")
    str(top_movies_urls)

    tidy_movies <- top_movies_urls %>%
      unnest_tokens(word, text) %>%
      anti_join(get_stopwords()) %>%
      count(word, sort = TRUE)
    ```

3.  Pull data on a specific user

    ```{r}
    user <- "thisisbillgates"
    bill_gates_user <- get_user_content(user)
    write_rds(bill_gates_user, "billgatesuser.rds")

    bill_gates_user <- read_rds("billgatesuser.rds")
    str(bill_gates_user)

    str(bill_gates_user[[user]]$about)

    str(bill_gates_user[[user]]$comments)

    str(bill_gates_user[[user]]$threads)

    basecomments <- bill_gates_user[[user]]$comments %>%
      tibble() %>%
      filter(score > 40)
    basecomments

    words <- basecomments %>%
      unnest_tokens(word, comment) %>%
      anti_join(stop_words)

    word_counts <- words %>%
      count(word, sort = TRUE)
    ```
